// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: hermes_bridge.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "hermes_bridge.v1";

/**
 * Every WebSocket message is exactly one serialized `Frame`. The receiver
 * parses once and switches on the `payload` oneof discriminant.
 *
 * Field numbers are partitioned by direction so additions stay readable:
 *   1-8    inbound (client -> server) control frames
 *   11-21  outbound (server -> client) control frames
 *   99     audio data (bidirectional; sent in bulk between audio_start and
 *          audio_stop)
 */
export interface Frame {
  hello?: HelloFrame | undefined;
  text?: TextFrame | undefined;
  audioStart?: AudioStartFrame | undefined;
  audioStop?: AudioStopFrame | undefined;
  sessionsList?: SessionsListFrame | undefined;
  sessionsSwitch?: SessionsSwitchFrame | undefined;
  sessionsNew?: SessionsNewFrame | undefined;
  stop?: StopFrame | undefined;
  helloOk?: HelloOkFrame | undefined;
  assistantDelta?: AssistantDeltaFrame | undefined;
  assistant?: AssistantFullFrame | undefined;
  toolStart?: ToolStartFrame | undefined;
  toolEnd?: ToolEndFrame | undefined;
  turnDone?: TurnDoneFrame | undefined;
  sessions?: SessionsFrame | undefined;
  active?: ActiveFrame | undefined;
  history?: HistoryFrame | undefined;
  transcript?: TranscriptFrame | undefined;
  error?: ErrorFrame | undefined;
  audioData?: AudioDataFrame | undefined;
}

/**
 * First frame on every connection. Authenticates the client and identifies
 * the glasses device. Server replies with HelloOkFrame or closes with 1008.
 */
export interface HelloFrame {
  token: string;
  /** defaults to "g2" if omitted */
  device: string;
}

/** User-typed text message. Forwarded to the gateway as a TEXT MessageEvent. */
export interface TextFrame {
  content: string;
}

/**
 * Signals the start of an audio capture stream. Subsequent AudioDataFrames
 * are accumulated until AudioStopFrame arrives.
 */
export interface AudioStartFrame {
}

/**
 * Signals the end of an audio capture stream. The accumulated PCM is
 * dispatched to ASR and the resulting transcript is forwarded to the gateway.
 */
export interface AudioStopFrame {
}

/**
 * Requests the server's session list for this chat_id. Server replies with
 * SessionsFrame.
 */
export interface SessionsListFrame {
}

/**
 * Requests an active-session switch. Target is either a relative offset
 * ("+1", "-1") or an absolute session id.
 */
export interface SessionsSwitchFrame {
  /** e.g. "+1", "-1", or "s-abc123" */
  target: string;
}

/**
 * Requests creation of a new session. Server replies with ActiveFrame once
 * the gateway has bound the new session id.
 */
export interface SessionsNewFrame {
}

/** Requests interruption of any in-flight assistant turn. */
export interface StopFrame {
}

/**
 * Successful handshake response. `active` carries the bound session id when
 * known (returning connection); omitted on first-ever connect.
 */
export interface HelloOkFrame {
  /** session id when known */
  active?:
    | string
    | undefined;
  /** server capabilities, e.g. "streaming" */
  caps: string[];
}

/**
 * Incremental assistant text delta. The glasses-app accumulates these into
 * the assistant reply container.
 */
export interface AssistantDeltaFrame {
  text: string;
}

/**
 * Full assistant reply (non-streaming path). Replaces any accumulated delta
 * state in one shot.
 */
export interface AssistantFullFrame {
  text: string;
}

/**
 * Signals that the agent has started calling a tool. The glasses-app renders
 * a "tool running" status line.
 */
export interface ToolStartFrame {
  name: string;
  /** human-readable, e.g. "web_search: weather today" */
  label?: string | undefined;
  emoji?: string | undefined;
}

/** Signals that a tool call has completed. */
export interface ToolEndFrame {
  name: string;
  /** false on error */
  ok: boolean;
}

/**
 * Signals the end of an assistant turn. The glasses-app marks the reply as
 * complete and stops the streaming cursor animation.
 */
export interface TurnDoneFrame {
}

/**
 * Server response to SessionsListFrame. `items` is the per-chat_id session
 * list; `active` is the currently-bound session id (if any).
 */
export interface SessionsFrame {
  items: SessionItem[];
  active?: string | undefined;
}

/** One entry in a session list or history. */
export interface SessionItem {
  id: string;
  /** human-readable name when available */
  name?: string | undefined;
}

/**
 * Informs the glasses-app that the active session has changed (either because
 * the user requested a switch or because the gateway created a new one).
 */
export interface ActiveFrame {
  id: string;
  /** falls back to id[:16] when absent */
  name?: string | undefined;
}

/**
 * Conversation history for a session. Currently unused on the wire but kept
 * in the schema for future server-side history push.
 */
export interface HistoryFrame {
  /** session id */
  id: string;
  items: HistoryItem[];
  /** false if the server couldn't fetch history */
  ok: boolean;
}

/** One turn in a conversation history. */
export interface HistoryItem {
  /** "user" | "assistant" | "system" */
  role: string;
  content: string;
}

/**
 * Transcript of the user's spoken audio, post-ASR. Displayed briefly so the
 * user can confirm what the glasses heard.
 */
export interface TranscriptFrame {
  text: string;
}

/** Generic error frame. Displayed in the status line on the glasses. */
export interface ErrorFrame {
  msg: string;
}

/**
 * Raw PCM audio chunk sent from glasses to server during an active audio
 * capture (between AudioStartFrame and AudioStopFrame).
 *
 * Format: signed 16-bit little-endian integers, 16 kHz, mono. Wrapping these
 * in a Frame variant (rather than sending as raw WS binary messages) lets
 * every WS message self-describe its type — eliminates the previous
 * `isinstance(raw, bytes)` heuristic in server.py.
 */
export interface AudioDataFrame {
  pcm: Uint8Array;
}

function createBaseFrame(): Frame {
  return {
    hello: undefined,
    text: undefined,
    audioStart: undefined,
    audioStop: undefined,
    sessionsList: undefined,
    sessionsSwitch: undefined,
    sessionsNew: undefined,
    stop: undefined,
    helloOk: undefined,
    assistantDelta: undefined,
    assistant: undefined,
    toolStart: undefined,
    toolEnd: undefined,
    turnDone: undefined,
    sessions: undefined,
    active: undefined,
    history: undefined,
    transcript: undefined,
    error: undefined,
    audioData: undefined,
  };
}

export const Frame: MessageFns<Frame> = {
  encode(message: Frame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hello !== undefined) {
      HelloFrame.encode(message.hello, writer.uint32(10).fork()).join();
    }
    if (message.text !== undefined) {
      TextFrame.encode(message.text, writer.uint32(18).fork()).join();
    }
    if (message.audioStart !== undefined) {
      AudioStartFrame.encode(message.audioStart, writer.uint32(26).fork()).join();
    }
    if (message.audioStop !== undefined) {
      AudioStopFrame.encode(message.audioStop, writer.uint32(34).fork()).join();
    }
    if (message.sessionsList !== undefined) {
      SessionsListFrame.encode(message.sessionsList, writer.uint32(42).fork()).join();
    }
    if (message.sessionsSwitch !== undefined) {
      SessionsSwitchFrame.encode(message.sessionsSwitch, writer.uint32(50).fork()).join();
    }
    if (message.sessionsNew !== undefined) {
      SessionsNewFrame.encode(message.sessionsNew, writer.uint32(58).fork()).join();
    }
    if (message.stop !== undefined) {
      StopFrame.encode(message.stop, writer.uint32(66).fork()).join();
    }
    if (message.helloOk !== undefined) {
      HelloOkFrame.encode(message.helloOk, writer.uint32(90).fork()).join();
    }
    if (message.assistantDelta !== undefined) {
      AssistantDeltaFrame.encode(message.assistantDelta, writer.uint32(98).fork()).join();
    }
    if (message.assistant !== undefined) {
      AssistantFullFrame.encode(message.assistant, writer.uint32(106).fork()).join();
    }
    if (message.toolStart !== undefined) {
      ToolStartFrame.encode(message.toolStart, writer.uint32(114).fork()).join();
    }
    if (message.toolEnd !== undefined) {
      ToolEndFrame.encode(message.toolEnd, writer.uint32(122).fork()).join();
    }
    if (message.turnDone !== undefined) {
      TurnDoneFrame.encode(message.turnDone, writer.uint32(130).fork()).join();
    }
    if (message.sessions !== undefined) {
      SessionsFrame.encode(message.sessions, writer.uint32(138).fork()).join();
    }
    if (message.active !== undefined) {
      ActiveFrame.encode(message.active, writer.uint32(146).fork()).join();
    }
    if (message.history !== undefined) {
      HistoryFrame.encode(message.history, writer.uint32(154).fork()).join();
    }
    if (message.transcript !== undefined) {
      TranscriptFrame.encode(message.transcript, writer.uint32(162).fork()).join();
    }
    if (message.error !== undefined) {
      ErrorFrame.encode(message.error, writer.uint32(170).fork()).join();
    }
    if (message.audioData !== undefined) {
      AudioDataFrame.encode(message.audioData, writer.uint32(794).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Frame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hello = HelloFrame.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = TextFrame.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.audioStart = AudioStartFrame.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.audioStop = AudioStopFrame.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sessionsList = SessionsListFrame.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sessionsSwitch = SessionsSwitchFrame.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sessionsNew = SessionsNewFrame.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.stop = StopFrame.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.helloOk = HelloOkFrame.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.assistantDelta = AssistantDeltaFrame.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.assistant = AssistantFullFrame.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.toolStart = ToolStartFrame.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.toolEnd = ToolEndFrame.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.turnDone = TurnDoneFrame.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.sessions = SessionsFrame.decode(reader, reader.uint32());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.active = ActiveFrame.decode(reader, reader.uint32());
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.history = HistoryFrame.decode(reader, reader.uint32());
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.transcript = TranscriptFrame.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.error = ErrorFrame.decode(reader, reader.uint32());
          continue;
        }
        case 99: {
          if (tag !== 794) {
            break;
          }

          message.audioData = AudioDataFrame.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Frame {
    return {
      hello: isSet(object.hello) ? HelloFrame.fromJSON(object.hello) : undefined,
      text: isSet(object.text) ? TextFrame.fromJSON(object.text) : undefined,
      audioStart: isSet(object.audioStart)
        ? AudioStartFrame.fromJSON(object.audioStart)
        : isSet(object.audio_start)
        ? AudioStartFrame.fromJSON(object.audio_start)
        : undefined,
      audioStop: isSet(object.audioStop)
        ? AudioStopFrame.fromJSON(object.audioStop)
        : isSet(object.audio_stop)
        ? AudioStopFrame.fromJSON(object.audio_stop)
        : undefined,
      sessionsList: isSet(object.sessionsList)
        ? SessionsListFrame.fromJSON(object.sessionsList)
        : isSet(object.sessions_list)
        ? SessionsListFrame.fromJSON(object.sessions_list)
        : undefined,
      sessionsSwitch: isSet(object.sessionsSwitch)
        ? SessionsSwitchFrame.fromJSON(object.sessionsSwitch)
        : isSet(object.sessions_switch)
        ? SessionsSwitchFrame.fromJSON(object.sessions_switch)
        : undefined,
      sessionsNew: isSet(object.sessionsNew)
        ? SessionsNewFrame.fromJSON(object.sessionsNew)
        : isSet(object.sessions_new)
        ? SessionsNewFrame.fromJSON(object.sessions_new)
        : undefined,
      stop: isSet(object.stop) ? StopFrame.fromJSON(object.stop) : undefined,
      helloOk: isSet(object.helloOk)
        ? HelloOkFrame.fromJSON(object.helloOk)
        : isSet(object.hello_ok)
        ? HelloOkFrame.fromJSON(object.hello_ok)
        : undefined,
      assistantDelta: isSet(object.assistantDelta)
        ? AssistantDeltaFrame.fromJSON(object.assistantDelta)
        : isSet(object.assistant_delta)
        ? AssistantDeltaFrame.fromJSON(object.assistant_delta)
        : undefined,
      assistant: isSet(object.assistant) ? AssistantFullFrame.fromJSON(object.assistant) : undefined,
      toolStart: isSet(object.toolStart)
        ? ToolStartFrame.fromJSON(object.toolStart)
        : isSet(object.tool_start)
        ? ToolStartFrame.fromJSON(object.tool_start)
        : undefined,
      toolEnd: isSet(object.toolEnd)
        ? ToolEndFrame.fromJSON(object.toolEnd)
        : isSet(object.tool_end)
        ? ToolEndFrame.fromJSON(object.tool_end)
        : undefined,
      turnDone: isSet(object.turnDone)
        ? TurnDoneFrame.fromJSON(object.turnDone)
        : isSet(object.turn_done)
        ? TurnDoneFrame.fromJSON(object.turn_done)
        : undefined,
      sessions: isSet(object.sessions) ? SessionsFrame.fromJSON(object.sessions) : undefined,
      active: isSet(object.active) ? ActiveFrame.fromJSON(object.active) : undefined,
      history: isSet(object.history) ? HistoryFrame.fromJSON(object.history) : undefined,
      transcript: isSet(object.transcript) ? TranscriptFrame.fromJSON(object.transcript) : undefined,
      error: isSet(object.error) ? ErrorFrame.fromJSON(object.error) : undefined,
      audioData: isSet(object.audioData)
        ? AudioDataFrame.fromJSON(object.audioData)
        : isSet(object.audio_data)
        ? AudioDataFrame.fromJSON(object.audio_data)
        : undefined,
    };
  },

  toJSON(message: Frame): unknown {
    const obj: any = {};
    if (message.hello !== undefined) {
      obj.hello = HelloFrame.toJSON(message.hello);
    }
    if (message.text !== undefined) {
      obj.text = TextFrame.toJSON(message.text);
    }
    if (message.audioStart !== undefined) {
      obj.audioStart = AudioStartFrame.toJSON(message.audioStart);
    }
    if (message.audioStop !== undefined) {
      obj.audioStop = AudioStopFrame.toJSON(message.audioStop);
    }
    if (message.sessionsList !== undefined) {
      obj.sessionsList = SessionsListFrame.toJSON(message.sessionsList);
    }
    if (message.sessionsSwitch !== undefined) {
      obj.sessionsSwitch = SessionsSwitchFrame.toJSON(message.sessionsSwitch);
    }
    if (message.sessionsNew !== undefined) {
      obj.sessionsNew = SessionsNewFrame.toJSON(message.sessionsNew);
    }
    if (message.stop !== undefined) {
      obj.stop = StopFrame.toJSON(message.stop);
    }
    if (message.helloOk !== undefined) {
      obj.helloOk = HelloOkFrame.toJSON(message.helloOk);
    }
    if (message.assistantDelta !== undefined) {
      obj.assistantDelta = AssistantDeltaFrame.toJSON(message.assistantDelta);
    }
    if (message.assistant !== undefined) {
      obj.assistant = AssistantFullFrame.toJSON(message.assistant);
    }
    if (message.toolStart !== undefined) {
      obj.toolStart = ToolStartFrame.toJSON(message.toolStart);
    }
    if (message.toolEnd !== undefined) {
      obj.toolEnd = ToolEndFrame.toJSON(message.toolEnd);
    }
    if (message.turnDone !== undefined) {
      obj.turnDone = TurnDoneFrame.toJSON(message.turnDone);
    }
    if (message.sessions !== undefined) {
      obj.sessions = SessionsFrame.toJSON(message.sessions);
    }
    if (message.active !== undefined) {
      obj.active = ActiveFrame.toJSON(message.active);
    }
    if (message.history !== undefined) {
      obj.history = HistoryFrame.toJSON(message.history);
    }
    if (message.transcript !== undefined) {
      obj.transcript = TranscriptFrame.toJSON(message.transcript);
    }
    if (message.error !== undefined) {
      obj.error = ErrorFrame.toJSON(message.error);
    }
    if (message.audioData !== undefined) {
      obj.audioData = AudioDataFrame.toJSON(message.audioData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Frame>, I>>(base?: I): Frame {
    return Frame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Frame>, I>>(object: I): Frame {
    const message = createBaseFrame();
    message.hello = (object.hello !== undefined && object.hello !== null)
      ? HelloFrame.fromPartial(object.hello)
      : undefined;
    message.text = (object.text !== undefined && object.text !== null) ? TextFrame.fromPartial(object.text) : undefined;
    message.audioStart = (object.audioStart !== undefined && object.audioStart !== null)
      ? AudioStartFrame.fromPartial(object.audioStart)
      : undefined;
    message.audioStop = (object.audioStop !== undefined && object.audioStop !== null)
      ? AudioStopFrame.fromPartial(object.audioStop)
      : undefined;
    message.sessionsList = (object.sessionsList !== undefined && object.sessionsList !== null)
      ? SessionsListFrame.fromPartial(object.sessionsList)
      : undefined;
    message.sessionsSwitch = (object.sessionsSwitch !== undefined && object.sessionsSwitch !== null)
      ? SessionsSwitchFrame.fromPartial(object.sessionsSwitch)
      : undefined;
    message.sessionsNew = (object.sessionsNew !== undefined && object.sessionsNew !== null)
      ? SessionsNewFrame.fromPartial(object.sessionsNew)
      : undefined;
    message.stop = (object.stop !== undefined && object.stop !== null) ? StopFrame.fromPartial(object.stop) : undefined;
    message.helloOk = (object.helloOk !== undefined && object.helloOk !== null)
      ? HelloOkFrame.fromPartial(object.helloOk)
      : undefined;
    message.assistantDelta = (object.assistantDelta !== undefined && object.assistantDelta !== null)
      ? AssistantDeltaFrame.fromPartial(object.assistantDelta)
      : undefined;
    message.assistant = (object.assistant !== undefined && object.assistant !== null)
      ? AssistantFullFrame.fromPartial(object.assistant)
      : undefined;
    message.toolStart = (object.toolStart !== undefined && object.toolStart !== null)
      ? ToolStartFrame.fromPartial(object.toolStart)
      : undefined;
    message.toolEnd = (object.toolEnd !== undefined && object.toolEnd !== null)
      ? ToolEndFrame.fromPartial(object.toolEnd)
      : undefined;
    message.turnDone = (object.turnDone !== undefined && object.turnDone !== null)
      ? TurnDoneFrame.fromPartial(object.turnDone)
      : undefined;
    message.sessions = (object.sessions !== undefined && object.sessions !== null)
      ? SessionsFrame.fromPartial(object.sessions)
      : undefined;
    message.active = (object.active !== undefined && object.active !== null)
      ? ActiveFrame.fromPartial(object.active)
      : undefined;
    message.history = (object.history !== undefined && object.history !== null)
      ? HistoryFrame.fromPartial(object.history)
      : undefined;
    message.transcript = (object.transcript !== undefined && object.transcript !== null)
      ? TranscriptFrame.fromPartial(object.transcript)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorFrame.fromPartial(object.error)
      : undefined;
    message.audioData = (object.audioData !== undefined && object.audioData !== null)
      ? AudioDataFrame.fromPartial(object.audioData)
      : undefined;
    return message;
  },
};

function createBaseHelloFrame(): HelloFrame {
  return { token: "", device: "" };
}

export const HelloFrame: MessageFns<HelloFrame> = {
  encode(message: HelloFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.device !== "") {
      writer.uint32(18).string(message.device);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.device = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloFrame {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      device: isSet(object.device) ? globalThis.String(object.device) : "",
    };
  },

  toJSON(message: HelloFrame): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.device !== "") {
      obj.device = message.device;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloFrame>, I>>(base?: I): HelloFrame {
    return HelloFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloFrame>, I>>(object: I): HelloFrame {
    const message = createBaseHelloFrame();
    message.token = object.token ?? "";
    message.device = object.device ?? "";
    return message;
  },
};

function createBaseTextFrame(): TextFrame {
  return { content: "" };
}

export const TextFrame: MessageFns<TextFrame> = {
  encode(message: TextFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TextFrame {
    return { content: isSet(object.content) ? globalThis.String(object.content) : "" };
  },

  toJSON(message: TextFrame): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TextFrame>, I>>(base?: I): TextFrame {
    return TextFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TextFrame>, I>>(object: I): TextFrame {
    const message = createBaseTextFrame();
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseAudioStartFrame(): AudioStartFrame {
  return {};
}

export const AudioStartFrame: MessageFns<AudioStartFrame> = {
  encode(_: AudioStartFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioStartFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioStartFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): AudioStartFrame {
    return {};
  },

  toJSON(_: AudioStartFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioStartFrame>, I>>(base?: I): AudioStartFrame {
    return AudioStartFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioStartFrame>, I>>(_: I): AudioStartFrame {
    const message = createBaseAudioStartFrame();
    return message;
  },
};

function createBaseAudioStopFrame(): AudioStopFrame {
  return {};
}

export const AudioStopFrame: MessageFns<AudioStopFrame> = {
  encode(_: AudioStopFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioStopFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioStopFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): AudioStopFrame {
    return {};
  },

  toJSON(_: AudioStopFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioStopFrame>, I>>(base?: I): AudioStopFrame {
    return AudioStopFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioStopFrame>, I>>(_: I): AudioStopFrame {
    const message = createBaseAudioStopFrame();
    return message;
  },
};

function createBaseSessionsListFrame(): SessionsListFrame {
  return {};
}

export const SessionsListFrame: MessageFns<SessionsListFrame> = {
  encode(_: SessionsListFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionsListFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionsListFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SessionsListFrame {
    return {};
  },

  toJSON(_: SessionsListFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionsListFrame>, I>>(base?: I): SessionsListFrame {
    return SessionsListFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionsListFrame>, I>>(_: I): SessionsListFrame {
    const message = createBaseSessionsListFrame();
    return message;
  },
};

function createBaseSessionsSwitchFrame(): SessionsSwitchFrame {
  return { target: "" };
}

export const SessionsSwitchFrame: MessageFns<SessionsSwitchFrame> = {
  encode(message: SessionsSwitchFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.target !== "") {
      writer.uint32(10).string(message.target);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionsSwitchFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionsSwitchFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.target = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionsSwitchFrame {
    return { target: isSet(object.target) ? globalThis.String(object.target) : "" };
  },

  toJSON(message: SessionsSwitchFrame): unknown {
    const obj: any = {};
    if (message.target !== "") {
      obj.target = message.target;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionsSwitchFrame>, I>>(base?: I): SessionsSwitchFrame {
    return SessionsSwitchFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionsSwitchFrame>, I>>(object: I): SessionsSwitchFrame {
    const message = createBaseSessionsSwitchFrame();
    message.target = object.target ?? "";
    return message;
  },
};

function createBaseSessionsNewFrame(): SessionsNewFrame {
  return {};
}

export const SessionsNewFrame: MessageFns<SessionsNewFrame> = {
  encode(_: SessionsNewFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionsNewFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionsNewFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SessionsNewFrame {
    return {};
  },

  toJSON(_: SessionsNewFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionsNewFrame>, I>>(base?: I): SessionsNewFrame {
    return SessionsNewFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionsNewFrame>, I>>(_: I): SessionsNewFrame {
    const message = createBaseSessionsNewFrame();
    return message;
  },
};

function createBaseStopFrame(): StopFrame {
  return {};
}

export const StopFrame: MessageFns<StopFrame> = {
  encode(_: StopFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): StopFrame {
    return {};
  },

  toJSON(_: StopFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<StopFrame>, I>>(base?: I): StopFrame {
    return StopFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopFrame>, I>>(_: I): StopFrame {
    const message = createBaseStopFrame();
    return message;
  },
};

function createBaseHelloOkFrame(): HelloOkFrame {
  return { active: undefined, caps: [] };
}

export const HelloOkFrame: MessageFns<HelloOkFrame> = {
  encode(message: HelloOkFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.active !== undefined) {
      writer.uint32(10).string(message.active);
    }
    for (const v of message.caps) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloOkFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloOkFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.active = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.caps.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloOkFrame {
    return {
      active: isSet(object.active) ? globalThis.String(object.active) : undefined,
      caps: globalThis.Array.isArray(object?.caps) ? object.caps.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: HelloOkFrame): unknown {
    const obj: any = {};
    if (message.active !== undefined) {
      obj.active = message.active;
    }
    if (message.caps?.length) {
      obj.caps = message.caps;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloOkFrame>, I>>(base?: I): HelloOkFrame {
    return HelloOkFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloOkFrame>, I>>(object: I): HelloOkFrame {
    const message = createBaseHelloOkFrame();
    message.active = object.active ?? undefined;
    message.caps = object.caps?.map((e) => e) || [];
    return message;
  },
};

function createBaseAssistantDeltaFrame(): AssistantDeltaFrame {
  return { text: "" };
}

export const AssistantDeltaFrame: MessageFns<AssistantDeltaFrame> = {
  encode(message: AssistantDeltaFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssistantDeltaFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssistantDeltaFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssistantDeltaFrame {
    return { text: isSet(object.text) ? globalThis.String(object.text) : "" };
  },

  toJSON(message: AssistantDeltaFrame): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssistantDeltaFrame>, I>>(base?: I): AssistantDeltaFrame {
    return AssistantDeltaFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssistantDeltaFrame>, I>>(object: I): AssistantDeltaFrame {
    const message = createBaseAssistantDeltaFrame();
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseAssistantFullFrame(): AssistantFullFrame {
  return { text: "" };
}

export const AssistantFullFrame: MessageFns<AssistantFullFrame> = {
  encode(message: AssistantFullFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssistantFullFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssistantFullFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssistantFullFrame {
    return { text: isSet(object.text) ? globalThis.String(object.text) : "" };
  },

  toJSON(message: AssistantFullFrame): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssistantFullFrame>, I>>(base?: I): AssistantFullFrame {
    return AssistantFullFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssistantFullFrame>, I>>(object: I): AssistantFullFrame {
    const message = createBaseAssistantFullFrame();
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseToolStartFrame(): ToolStartFrame {
  return { name: "", label: undefined, emoji: undefined };
}

export const ToolStartFrame: MessageFns<ToolStartFrame> = {
  encode(message: ToolStartFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.label !== undefined) {
      writer.uint32(18).string(message.label);
    }
    if (message.emoji !== undefined) {
      writer.uint32(26).string(message.emoji);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolStartFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolStartFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.emoji = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolStartFrame {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : undefined,
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : undefined,
    };
  },

  toJSON(message: ToolStartFrame): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.label !== undefined) {
      obj.label = message.label;
    }
    if (message.emoji !== undefined) {
      obj.emoji = message.emoji;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolStartFrame>, I>>(base?: I): ToolStartFrame {
    return ToolStartFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolStartFrame>, I>>(object: I): ToolStartFrame {
    const message = createBaseToolStartFrame();
    message.name = object.name ?? "";
    message.label = object.label ?? undefined;
    message.emoji = object.emoji ?? undefined;
    return message;
  },
};

function createBaseToolEndFrame(): ToolEndFrame {
  return { name: "", ok: false };
}

export const ToolEndFrame: MessageFns<ToolEndFrame> = {
  encode(message: ToolEndFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.ok !== false) {
      writer.uint32(16).bool(message.ok);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolEndFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolEndFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolEndFrame {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
    };
  },

  toJSON(message: ToolEndFrame): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolEndFrame>, I>>(base?: I): ToolEndFrame {
    return ToolEndFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolEndFrame>, I>>(object: I): ToolEndFrame {
    const message = createBaseToolEndFrame();
    message.name = object.name ?? "";
    message.ok = object.ok ?? false;
    return message;
  },
};

function createBaseTurnDoneFrame(): TurnDoneFrame {
  return {};
}

export const TurnDoneFrame: MessageFns<TurnDoneFrame> = {
  encode(_: TurnDoneFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TurnDoneFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTurnDoneFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TurnDoneFrame {
    return {};
  },

  toJSON(_: TurnDoneFrame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TurnDoneFrame>, I>>(base?: I): TurnDoneFrame {
    return TurnDoneFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TurnDoneFrame>, I>>(_: I): TurnDoneFrame {
    const message = createBaseTurnDoneFrame();
    return message;
  },
};

function createBaseSessionsFrame(): SessionsFrame {
  return { items: [], active: undefined };
}

export const SessionsFrame: MessageFns<SessionsFrame> = {
  encode(message: SessionsFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      SessionItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.active !== undefined) {
      writer.uint32(18).string(message.active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionsFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionsFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(SessionItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.active = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionsFrame {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => SessionItem.fromJSON(e)) : [],
      active: isSet(object.active) ? globalThis.String(object.active) : undefined,
    };
  },

  toJSON(message: SessionsFrame): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => SessionItem.toJSON(e));
    }
    if (message.active !== undefined) {
      obj.active = message.active;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionsFrame>, I>>(base?: I): SessionsFrame {
    return SessionsFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionsFrame>, I>>(object: I): SessionsFrame {
    const message = createBaseSessionsFrame();
    message.items = object.items?.map((e) => SessionItem.fromPartial(e)) || [];
    message.active = object.active ?? undefined;
    return message;
  },
};

function createBaseSessionItem(): SessionItem {
  return { id: "", name: undefined };
}

export const SessionItem: MessageFns<SessionItem> = {
  encode(message: SessionItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
    };
  },

  toJSON(message: SessionItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionItem>, I>>(base?: I): SessionItem {
    return SessionItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionItem>, I>>(object: I): SessionItem {
    const message = createBaseSessionItem();
    message.id = object.id ?? "";
    message.name = object.name ?? undefined;
    return message;
  },
};

function createBaseActiveFrame(): ActiveFrame {
  return { id: "", name: undefined };
}

export const ActiveFrame: MessageFns<ActiveFrame> = {
  encode(message: ActiveFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActiveFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActiveFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActiveFrame {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
    };
  },

  toJSON(message: ActiveFrame): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveFrame>, I>>(base?: I): ActiveFrame {
    return ActiveFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveFrame>, I>>(object: I): ActiveFrame {
    const message = createBaseActiveFrame();
    message.id = object.id ?? "";
    message.name = object.name ?? undefined;
    return message;
  },
};

function createBaseHistoryFrame(): HistoryFrame {
  return { id: "", items: [], ok: false };
}

export const HistoryFrame: MessageFns<HistoryFrame> = {
  encode(message: HistoryFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.items) {
      HistoryItem.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.ok !== false) {
      writer.uint32(24).bool(message.ok);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(HistoryItem.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryFrame {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => HistoryItem.fromJSON(e)) : [],
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
    };
  },

  toJSON(message: HistoryFrame): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => HistoryItem.toJSON(e));
    }
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryFrame>, I>>(base?: I): HistoryFrame {
    return HistoryFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryFrame>, I>>(object: I): HistoryFrame {
    const message = createBaseHistoryFrame();
    message.id = object.id ?? "";
    message.items = object.items?.map((e) => HistoryItem.fromPartial(e)) || [];
    message.ok = object.ok ?? false;
    return message;
  },
};

function createBaseHistoryItem(): HistoryItem {
  return { role: "", content: "" };
}

export const HistoryItem: MessageFns<HistoryItem> = {
  encode(message: HistoryItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.role !== "") {
      writer.uint32(10).string(message.role);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryItem {
    return {
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: HistoryItem): unknown {
    const obj: any = {};
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryItem>, I>>(base?: I): HistoryItem {
    return HistoryItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryItem>, I>>(object: I): HistoryItem {
    const message = createBaseHistoryItem();
    message.role = object.role ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseTranscriptFrame(): TranscriptFrame {
  return { text: "" };
}

export const TranscriptFrame: MessageFns<TranscriptFrame> = {
  encode(message: TranscriptFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptFrame {
    return { text: isSet(object.text) ? globalThis.String(object.text) : "" };
  },

  toJSON(message: TranscriptFrame): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptFrame>, I>>(base?: I): TranscriptFrame {
    return TranscriptFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptFrame>, I>>(object: I): TranscriptFrame {
    const message = createBaseTranscriptFrame();
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseErrorFrame(): ErrorFrame {
  return { msg: "" };
}

export const ErrorFrame: MessageFns<ErrorFrame> = {
  encode(message: ErrorFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== "") {
      writer.uint32(10).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorFrame {
    return { msg: isSet(object.msg) ? globalThis.String(object.msg) : "" };
  },

  toJSON(message: ErrorFrame): unknown {
    const obj: any = {};
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorFrame>, I>>(base?: I): ErrorFrame {
    return ErrorFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorFrame>, I>>(object: I): ErrorFrame {
    const message = createBaseErrorFrame();
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseAudioDataFrame(): AudioDataFrame {
  return { pcm: new Uint8Array(0) };
}

export const AudioDataFrame: MessageFns<AudioDataFrame> = {
  encode(message: AudioDataFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pcm.length !== 0) {
      writer.uint32(10).bytes(message.pcm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioDataFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioDataFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pcm = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioDataFrame {
    return { pcm: isSet(object.pcm) ? bytesFromBase64(object.pcm) : new Uint8Array(0) };
  },

  toJSON(message: AudioDataFrame): unknown {
    const obj: any = {};
    if (message.pcm.length !== 0) {
      obj.pcm = base64FromBytes(message.pcm);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioDataFrame>, I>>(base?: I): AudioDataFrame {
    return AudioDataFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioDataFrame>, I>>(object: I): AudioDataFrame {
    const message = createBaseAudioDataFrame();
    message.pcm = object.pcm ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
