"""Emit glasses-app/src/protocol.ts from protocol.py.

Run after modifying protocol.py. CI should fail if the committed .ts file
doesn't match the freshly-generated one.

Usage:
    uv run python -m byoa_plugin.protocol_gen --out ../../glasses-app/src/protocol.ts
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add this module's package to the path so we can import without install
sys.path.insert(0, str(Path(__file__).resolve().parent))

from byoa_plugin import protocol as proto

TEMPLATE = """\
// AUTO-GENERATED by plugin/src/byoa_plugin/protocol_gen.py — DO NOT EDIT.
// Regenerate with: uv run python -m byoa_plugin.protocol_gen

export const STREAMING_CURSOR = {cursor!r};

// Frame type literals for exhaustive matching.
export type InboundFrameType =
{inbound_types};

export type OutboundFrameType =
{outbound_types};

// Inbound frame shapes (client → server).
export interface HelloFrame {{
  t: 'hello';
  token: string;
  device?: string;
}}

export interface TextFrame {{
  t: 'text';
  text: string;
}}

export interface AudioStartFrame {{
  t: 'audio.start';
}}

export interface AudioStopFrame {{
  t: 'audio.stop';
}}

export interface SessionsSwitchFrame {{
  t: 'sessions.switch';
  id: string;  // session id or "+1"/"-1"
}}

export interface SimpleInboundFrame {{
  t: 'sessions.list' | 'sessions.new' | 'stop';
}}

export type InboundFrame =
  | HelloFrame
  | TextFrame
  | AudioStartFrame
  | AudioStopFrame
  | SessionsSwitchFrame
  | SimpleInboundFrame;

// Outbound frame shapes (server → client).
export interface HelloOkFrame {{
  t: 'hello.ok';
  active?: string;
  caps?: string[];
}}

export interface AssistantDeltaFrame {{
  t: 'assistant.delta';
  text: string;
}}

export interface AssistantFullFrame {{
  t: 'assistant';
  text: string;
}}

export interface ToolStartFrame {{
  t: 'tool.start';
  name: string;
  label?: string;
  emoji?: string;
}}

export interface ToolEndFrame {{
  t: 'tool.end';
  name: string;
  ok: boolean;
}}

export interface TurnDoneFrame {{
  t: 'turn.done';
}}

export interface SessionsFrame {{
  t: 'sessions';
  items: Array<{{ id: string; name?: string }}>;
  active?: string;
}}

export interface ActiveFrame {{
  t: 'active';
  id: string;
  name?: string;
}}

export interface HistoryFrame {{
  t: 'history';
  id: string;
  items: Array<{{ role: string; content: string }}>;
  ok: boolean;
}}

export interface TranscriptFrame {{
  t: 'transcript';
  text: string;
}}

export interface ErrorFrame {{
  t: 'error';
  msg: string;
}}

export type OutboundFrame =
  | HelloOkFrame
  | AssistantDeltaFrame
  | AssistantFullFrame
  | ToolStartFrame
  | ToolEndFrame
  | TurnDoneFrame
  | SessionsFrame
  | ActiveFrame
  | HistoryFrame
  | TranscriptFrame
  | ErrorFrame;

// Convenience functions for sending inbound frames over the WebSocket.
export const sendHello = (ws: WebSocket, token: string, device: string = 'g2') =>
  ws.send(JSON.stringify({{ t: 'hello', token, device }}));

export const sendText = (ws: WebSocket, text: string) =>
  ws.send(JSON.stringify({{ t: 'text', text }}));

export const sendAudioStart = (ws: WebSocket) =>
  ws.send(JSON.stringify({{ t: 'audio.start' }}));

export const sendAudioStop = (ws: WebSocket) =>
  ws.send(JSON.stringify({{ t: 'audio.stop' }}));

export const sendSessionsList = (ws: WebSocket) =>
  ws.send(JSON.stringify({{ t: 'sessions.list' }}));

export const sendSessionsSwitch = (ws: WebSocket, id: string) =>
  ws.send(JSON.stringify({{ t: 'sessions.switch', id }}));

export const sendSessionsNew = (ws: WebSocket) =>
  ws.send(JSON.stringify({{ t: 'sessions.new' }}));

export const sendStop = (ws: WebSocket) =>
  ws.send(JSON.stringify({{ t: 'stop' }}));

// Parse an outbound frame received from the server.
export const parseOutbound = (raw: string): OutboundFrame => JSON.parse(raw);
"""


def _format_union(types: tuple[str, ...]) -> str:
    indent = "  | "
    joined = f"{indent}".join(repr(t) for t in types)
    return f"{joined};"


def generate() -> str:
    """Return the generated TypeScript protocol source."""
    return TEMPLATE.format(
        cursor=proto.STREAMING_CURSOR,
        inbound_types=_format_union(proto.INBOUND_TYPES),
        outbound_types=_format_union(proto.OUTBOUND_TYPES),
    )


def main() -> int:
    """Run the CLI and print or write the generated TypeScript source."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=None,
        help="Output path for protocol.ts. Prints to stdout if omitted.",
    )
    args = parser.parse_args()
    content = generate()
    if args.out:
        Path(args.out).write_text(content, encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)  # noqa: T201 - CLI tool output
    else:
        print(content)  # noqa: T201 - CLI tool output
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
