"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Hermes Bridge Wire Protocol

Single source of truth for every frame exchanged between the even-g2 plugin
(Python, server side) and the glasses-app (TypeScript, client side) over
their WebSocket connection.

Migration history: this .proto replaced the hand-rolled JSON-over-WebSocket
protocol defined in the former `plugin/src/byoa_plugin/protocol.py`. See
openspec/changes/protobuf-wire-protocol/ for the design rationale.

FIELD NUMBER STABILITY: Protobuf wire compatibility depends on field
numbers, not names. NEVER renumber existing fields. Renaming a field is
safe; recycling a retired field number is not. New frame types get the
next free oneof variant number.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Frame(_message.Message):
    """============================================================================
    Frame envelope
    ============================================================================

    Every WebSocket message is exactly one serialized `Frame`. The receiver
    parses once and switches on the `payload` oneof discriminant.

    Field numbers are partitioned by direction so additions stay readable:
      1-8    inbound (client -> server) control frames
      11-21  outbound (server -> client) control frames
      99     audio data (bidirectional; sent in bulk between audio_start and
             audio_stop)
    """

    DESCRIPTOR: _descriptor.Descriptor

    HELLO_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    AUDIO_START_FIELD_NUMBER: _builtins.int
    AUDIO_STOP_FIELD_NUMBER: _builtins.int
    SESSIONS_LIST_FIELD_NUMBER: _builtins.int
    SESSIONS_SWITCH_FIELD_NUMBER: _builtins.int
    SESSIONS_NEW_FIELD_NUMBER: _builtins.int
    STOP_FIELD_NUMBER: _builtins.int
    HELLO_OK_FIELD_NUMBER: _builtins.int
    ASSISTANT_DELTA_FIELD_NUMBER: _builtins.int
    ASSISTANT_FIELD_NUMBER: _builtins.int
    TOOL_START_FIELD_NUMBER: _builtins.int
    TOOL_END_FIELD_NUMBER: _builtins.int
    TURN_DONE_FIELD_NUMBER: _builtins.int
    SESSIONS_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    AUDIO_DATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hello(self) -> Global___HelloFrame: ...
    @_builtins.property
    def text(self) -> Global___TextFrame: ...
    @_builtins.property
    def audio_start(self) -> Global___AudioStartFrame: ...
    @_builtins.property
    def audio_stop(self) -> Global___AudioStopFrame: ...
    @_builtins.property
    def sessions_list(self) -> Global___SessionsListFrame: ...
    @_builtins.property
    def sessions_switch(self) -> Global___SessionsSwitchFrame: ...
    @_builtins.property
    def sessions_new(self) -> Global___SessionsNewFrame: ...
    @_builtins.property
    def stop(self) -> Global___StopFrame: ...
    @_builtins.property
    def hello_ok(self) -> Global___HelloOkFrame: ...
    @_builtins.property
    def assistant_delta(self) -> Global___AssistantDeltaFrame: ...
    @_builtins.property
    def assistant(self) -> Global___AssistantFullFrame: ...
    @_builtins.property
    def tool_start(self) -> Global___ToolStartFrame: ...
    @_builtins.property
    def tool_end(self) -> Global___ToolEndFrame: ...
    @_builtins.property
    def turn_done(self) -> Global___TurnDoneFrame: ...
    @_builtins.property
    def sessions(self) -> Global___SessionsFrame: ...
    @_builtins.property
    def active(self) -> Global___ActiveFrame: ...
    @_builtins.property
    def history(self) -> Global___HistoryFrame: ...
    @_builtins.property
    def transcript(self) -> Global___TranscriptFrame: ...
    @_builtins.property
    def error(self) -> Global___ErrorFrame: ...
    @_builtins.property
    def audio_data(self) -> Global___AudioDataFrame: ...
    def __init__(
        self,
        *,
        hello: Global___HelloFrame | None = ...,
        text: Global___TextFrame | None = ...,
        audio_start: Global___AudioStartFrame | None = ...,
        audio_stop: Global___AudioStopFrame | None = ...,
        sessions_list: Global___SessionsListFrame | None = ...,
        sessions_switch: Global___SessionsSwitchFrame | None = ...,
        sessions_new: Global___SessionsNewFrame | None = ...,
        stop: Global___StopFrame | None = ...,
        hello_ok: Global___HelloOkFrame | None = ...,
        assistant_delta: Global___AssistantDeltaFrame | None = ...,
        assistant: Global___AssistantFullFrame | None = ...,
        tool_start: Global___ToolStartFrame | None = ...,
        tool_end: Global___ToolEndFrame | None = ...,
        turn_done: Global___TurnDoneFrame | None = ...,
        sessions: Global___SessionsFrame | None = ...,
        active: Global___ActiveFrame | None = ...,
        history: Global___HistoryFrame | None = ...,
        transcript: Global___TranscriptFrame | None = ...,
        error: Global___ErrorFrame | None = ...,
        audio_data: Global___AudioDataFrame | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "assistant", b"assistant", "assistant_delta", b"assistant_delta", "audio_data", b"audio_data", "audio_start", b"audio_start", "audio_stop", b"audio_stop", "error", b"error", "hello", b"hello", "hello_ok", b"hello_ok", "history", b"history", "payload", b"payload", "sessions", b"sessions", "sessions_list", b"sessions_list", "sessions_new", b"sessions_new", "sessions_switch", b"sessions_switch", "stop", b"stop", "text", b"text", "tool_end", b"tool_end", "tool_start", b"tool_start", "transcript", b"transcript", "turn_done", b"turn_done"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "assistant", b"assistant", "assistant_delta", b"assistant_delta", "audio_data", b"audio_data", "audio_start", b"audio_start", "audio_stop", b"audio_stop", "error", b"error", "hello", b"hello", "hello_ok", b"hello_ok", "history", b"history", "payload", b"payload", "sessions", b"sessions", "sessions_list", b"sessions_list", "sessions_new", b"sessions_new", "sessions_switch", b"sessions_switch", "stop", b"stop", "text", b"text", "tool_end", b"tool_end", "tool_start", b"tool_start", "transcript", b"transcript", "turn_done", b"turn_done"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["hello", "text", "audio_start", "audio_stop", "sessions_list", "sessions_switch", "sessions_new", "stop", "hello_ok", "assistant_delta", "assistant", "tool_start", "tool_end", "turn_done", "sessions", "active", "history", "transcript", "error", "audio_data"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___Frame: _TypeAlias = Frame  # noqa: Y015

@_typing.final
class HelloFrame(_message.Message):
    """============================================================================
    Inbound frames (client -> server)
    ============================================================================

    First frame on every connection. Authenticates the client and identifies
    the glasses device. Server replies with HelloOkFrame or closes with 1008.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    DEVICE_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    device: _builtins.str
    """defaults to "g2" if omitted"""
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
        device: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HelloFrame: _TypeAlias = HelloFrame  # noqa: Y015

@_typing.final
class TextFrame(_message.Message):
    """User-typed text message. Forwarded to the gateway as a TEXT MessageEvent."""

    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    content: _builtins.str
    def __init__(
        self,
        *,
        content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TextFrame: _TypeAlias = TextFrame  # noqa: Y015

@_typing.final
class AudioStartFrame(_message.Message):
    """Signals the start of an audio capture stream. Subsequent AudioDataFrames
    are accumulated until AudioStopFrame arrives.
    intentionally empty — signals intent only
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioStartFrame: _TypeAlias = AudioStartFrame  # noqa: Y015

@_typing.final
class AudioStopFrame(_message.Message):
    """Signals the end of an audio capture stream. The accumulated PCM is
    dispatched to ASR and the resulting transcript is forwarded to the gateway.
    intentionally empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioStopFrame: _TypeAlias = AudioStopFrame  # noqa: Y015

@_typing.final
class SessionsListFrame(_message.Message):
    """Requests the server's session list for this chat_id. Server replies with
    SessionsFrame.
    intentionally empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionsListFrame: _TypeAlias = SessionsListFrame  # noqa: Y015

@_typing.final
class SessionsSwitchFrame(_message.Message):
    """Requests an active-session switch. Target is either a relative offset
    ("+1", "-1") or an absolute session id.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    target: _builtins.str
    """e.g. "+1", "-1", or "s-abc123" """
    def __init__(
        self,
        *,
        target: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionsSwitchFrame: _TypeAlias = SessionsSwitchFrame  # noqa: Y015

@_typing.final
class SessionsNewFrame(_message.Message):
    """Requests creation of a new session. Server replies with ActiveFrame once
    the gateway has bound the new session id.
    intentionally empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionsNewFrame: _TypeAlias = SessionsNewFrame  # noqa: Y015

@_typing.final
class StopFrame(_message.Message):
    """Requests interruption of any in-flight assistant turn.
    intentionally empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopFrame: _TypeAlias = StopFrame  # noqa: Y015

@_typing.final
class HelloOkFrame(_message.Message):
    """============================================================================
    Outbound frames (server -> client)
    ============================================================================

    Successful handshake response. `active` carries the bound session id when
    known (returning connection); omitted on first-ever connect.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ACTIVE_FIELD_NUMBER: _builtins.int
    CAPS_FIELD_NUMBER: _builtins.int
    active: _builtins.str
    """session id when known"""
    @_builtins.property
    def caps(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """server capabilities, e.g. "streaming" """

    def __init__(
        self,
        *,
        active: _builtins.str | None = ...,
        caps: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_active", b"_active", "active", b"active"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_active", b"_active", "active", b"active", "caps", b"caps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__active: _TypeAlias = _typing.Literal["active"]  # noqa: Y015
    _WhichOneofArgType__active: _TypeAlias = _typing.Literal["_active", b"_active"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__active) -> _WhichOneofReturnType__active | None: ...

Global___HelloOkFrame: _TypeAlias = HelloOkFrame  # noqa: Y015

@_typing.final
class AssistantDeltaFrame(_message.Message):
    """Incremental assistant text delta. The glasses-app accumulates these into
    the assistant reply container.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssistantDeltaFrame: _TypeAlias = AssistantDeltaFrame  # noqa: Y015

@_typing.final
class AssistantFullFrame(_message.Message):
    """Full assistant reply (non-streaming path). Replaces any accumulated delta
    state in one shot.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssistantFullFrame: _TypeAlias = AssistantFullFrame  # noqa: Y015

@_typing.final
class ToolStartFrame(_message.Message):
    """Signals that the agent has started calling a tool. The glasses-app renders
    a "tool running" status line.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    EMOJI_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    label: _builtins.str
    """human-readable, e.g. "web_search: weather today" """
    emoji: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        label: _builtins.str | None = ...,
        emoji: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_emoji", b"_emoji", "_label", b"_label", "emoji", b"emoji", "label", b"label"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_emoji", b"_emoji", "_label", b"_label", "emoji", b"emoji", "label", b"label", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__emoji: _TypeAlias = _typing.Literal["emoji"]  # noqa: Y015
    _WhichOneofArgType__emoji: _TypeAlias = _typing.Literal["_emoji", b"_emoji"]  # noqa: Y015
    _WhichOneofReturnType__label: _TypeAlias = _typing.Literal["label"]  # noqa: Y015
    _WhichOneofArgType__label: _TypeAlias = _typing.Literal["_label", b"_label"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__emoji) -> _WhichOneofReturnType__emoji | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__label) -> _WhichOneofReturnType__label | None: ...

Global___ToolStartFrame: _TypeAlias = ToolStartFrame  # noqa: Y015

@_typing.final
class ToolEndFrame(_message.Message):
    """Signals that a tool call has completed."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    ok: _builtins.bool
    """false on error"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        ok: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ToolEndFrame: _TypeAlias = ToolEndFrame  # noqa: Y015

@_typing.final
class TurnDoneFrame(_message.Message):
    """Signals the end of an assistant turn. The glasses-app marks the reply as
    complete and stops the streaming cursor animation.
    intentionally empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TurnDoneFrame: _TypeAlias = TurnDoneFrame  # noqa: Y015

@_typing.final
class SessionsFrame(_message.Message):
    """Server response to SessionsListFrame. `items` is the per-chat_id session
    list; `active` is the currently-bound session id (if any).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    active: _builtins.str
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___SessionItem]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___SessionItem] | None = ...,
        active: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_active", b"_active", "active", b"active"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_active", b"_active", "active", b"active", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__active: _TypeAlias = _typing.Literal["active"]  # noqa: Y015
    _WhichOneofArgType__active: _TypeAlias = _typing.Literal["_active", b"_active"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__active) -> _WhichOneofReturnType__active | None: ...

Global___SessionsFrame: _TypeAlias = SessionsFrame  # noqa: Y015

@_typing.final
class SessionItem(_message.Message):
    """One entry in a session list or history."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    """human-readable name when available"""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___SessionItem: _TypeAlias = SessionItem  # noqa: Y015

@_typing.final
class ActiveFrame(_message.Message):
    """Informs the glasses-app that the active session has changed (either because
    the user requested a switch or because the gateway created a new one).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    """falls back to id[:16] when absent"""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___ActiveFrame: _TypeAlias = ActiveFrame  # noqa: Y015

@_typing.final
class HistoryFrame(_message.Message):
    """Conversation history for a session. Currently unused on the wire but kept
    in the schema for future server-side history push.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """session id"""
    ok: _builtins.bool
    """false if the server couldn't fetch history"""
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___HistoryItem]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        items: _abc.Iterable[Global___HistoryItem] | None = ...,
        ok: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "items", b"items", "ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HistoryFrame: _TypeAlias = HistoryFrame  # noqa: Y015

@_typing.final
class HistoryItem(_message.Message):
    """One turn in a conversation history."""

    DESCRIPTOR: _descriptor.Descriptor

    ROLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    role: _builtins.str
    """"user" | "assistant" | "system" """
    content: _builtins.str
    def __init__(
        self,
        *,
        role: _builtins.str = ...,
        content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "role", b"role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HistoryItem: _TypeAlias = HistoryItem  # noqa: Y015

@_typing.final
class TranscriptFrame(_message.Message):
    """Transcript of the user's spoken audio, post-ASR. Displayed briefly so the
    user can confirm what the glasses heard.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TranscriptFrame: _TypeAlias = TranscriptFrame  # noqa: Y015

@_typing.final
class ErrorFrame(_message.Message):
    """Generic error frame. Displayed in the status line on the glasses."""

    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    msg: _builtins.str
    def __init__(
        self,
        *,
        msg: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ErrorFrame: _TypeAlias = ErrorFrame  # noqa: Y015

@_typing.final
class AudioDataFrame(_message.Message):
    """============================================================================
    Bidirectional frames
    ============================================================================

    Raw PCM audio chunk sent from glasses to server during an active audio
    capture (between AudioStartFrame and AudioStopFrame).

    Format: signed 16-bit little-endian integers, 16 kHz, mono. Wrapping these
    in a Frame variant (rather than sending as raw WS binary messages) lets
    every WS message self-describe its type — eliminates the previous
    `isinstance(raw, bytes)` heuristic in server.py.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PCM_FIELD_NUMBER: _builtins.int
    pcm: _builtins.bytes
    def __init__(
        self,
        *,
        pcm: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pcm", b"pcm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioDataFrame: _TypeAlias = AudioDataFrame  # noqa: Y015
