// AUTO-GENERATED by plugin/src/byoa_plugin/protocol_gen.py — DO NOT EDIT.
// Regenerate with: uv run python -m byoa_plugin.protocol_gen

export const STREAMING_CURSOR = ' ▉';

// Frame type literals for exhaustive matching.
export type InboundFrameType =
'hello'  | 'text'  | 'audio.start'  | 'audio.stop'  | 'sessions.list'  | 'sessions.switch'  | 'sessions.new'  | 'stop';;

export type OutboundFrameType =
'hello.ok'  | 'assistant.delta'  | 'assistant'  | 'tool.start'  | 'tool.end'  | 'turn.done'  | 'sessions'  | 'active'  | 'history'  | 'transcript'  | 'error';;

// Inbound frame shapes (client → server).
export interface HelloFrame {
  t: 'hello';
  token: string;
  device?: string;
}

export interface TextFrame {
  t: 'text';
  text: string;
}

export interface AudioStartFrame {
  t: 'audio.start';
}

export interface AudioStopFrame {
  t: 'audio.stop';
}

export interface SessionsSwitchFrame {
  t: 'sessions.switch';
  id: string;  // session id or "+1"/"-1"
}

export interface SimpleInboundFrame {
  t: 'sessions.list' | 'sessions.new' | 'stop';
}

export type InboundFrame =
  | HelloFrame
  | TextFrame
  | AudioStartFrame
  | AudioStopFrame
  | SessionsSwitchFrame
  | SimpleInboundFrame;

// Outbound frame shapes (server → client).
export interface HelloOkFrame {
  t: 'hello.ok';
  active?: string;
  caps?: string[];
}

export interface AssistantDeltaFrame {
  t: 'assistant.delta';
  text: string;
}

export interface AssistantFullFrame {
  t: 'assistant';
  text: string;
}

export interface ToolStartFrame {
  t: 'tool.start';
  name: string;
  label?: string;
  emoji?: string;
}

export interface ToolEndFrame {
  t: 'tool.end';
  name: string;
  ok: boolean;
}

export interface TurnDoneFrame {
  t: 'turn.done';
}

export interface SessionsFrame {
  t: 'sessions';
  items: Array<{ id: string; name?: string }>;
  active?: string;
}

export interface ActiveFrame {
  t: 'active';
  id: string;
  name?: string;
}

export interface HistoryFrame {
  t: 'history';
  id: string;
  items: Array<{ role: string; content: string }>;
  ok: boolean;
}

export interface TranscriptFrame {
  t: 'transcript';
  text: string;
}

export interface ErrorFrame {
  t: 'error';
  msg: string;
}

export type OutboundFrame =
  | HelloOkFrame
  | AssistantDeltaFrame
  | AssistantFullFrame
  | ToolStartFrame
  | ToolEndFrame
  | TurnDoneFrame
  | SessionsFrame
  | ActiveFrame
  | HistoryFrame
  | TranscriptFrame
  | ErrorFrame;

// Convenience functions for sending inbound frames over the WebSocket.
export const sendHello = (ws: WebSocket, token: string, device: string = 'g2') =>
  ws.send(JSON.stringify({ t: 'hello', token, device }));

export const sendText = (ws: WebSocket, text: string) =>
  ws.send(JSON.stringify({ t: 'text', text }));

export const sendAudioStart = (ws: WebSocket) =>
  ws.send(JSON.stringify({ t: 'audio.start' }));

export const sendAudioStop = (ws: WebSocket) =>
  ws.send(JSON.stringify({ t: 'audio.stop' }));

export const sendSessionsList = (ws: WebSocket) =>
  ws.send(JSON.stringify({ t: 'sessions.list' }));

export const sendSessionsSwitch = (ws: WebSocket, id: string) =>
  ws.send(JSON.stringify({ t: 'sessions.switch', id }));

export const sendSessionsNew = (ws: WebSocket) =>
  ws.send(JSON.stringify({ t: 'sessions.new' }));

export const sendStop = (ws: WebSocket) =>
  ws.send(JSON.stringify({ t: 'stop' }));

// Parse an outbound frame received from the server.
export const parseOutbound = (raw: string): OutboundFrame => JSON.parse(raw);

